create extension if not exists pgcrypto;

create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table if not exists segments (
    id uuid primary key default gen_random_uuid(),
    name text,
    description text,
    color_hex text,
    created_at timestamptz not null default now(),
    updated_at timestamptz default now()
);

create table if not exists templates (
    id uuid primary key default gen_random_uuid(),
    template_name text not null,
    body text not null,
    category text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz default now()
);

create table if not exists contacts (
    id uuid primary key default gen_random_uuid(),
    full_name text,
    phone_no bigint,
    status text,
    segment_id uuid references segments(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz default now()
);

create table if not exists campaigns (
    id bigint generated by default as identity primary key,
    campaign_name text,
    segment_id uuid references segments(id) on delete set null,
    template_id uuid references templates(id) on delete set null,
    scheduled_date timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz default now()
);

create table if not exists profile (
    id uuid primary key references auth.users(id) on delete cascade,
    local_server jsonb,
    cloud_server jsonb,
    sim_slot int default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz default now()
);

drop trigger if exists segments_updated_at on segments;
create trigger segments_updated_at
    before update on segments
    for each row execute procedure set_updated_at();

drop trigger if exists templates_updated_at on templates;
create trigger templates_updated_at
    before update on templates
    for each row execute procedure set_updated_at();

drop trigger if exists contacts_updated_at on contacts;
create trigger contacts_updated_at
    before update on contacts
    for each row execute procedure set_updated_at();

drop trigger if exists campaigns_updated_at on campaigns;
create trigger campaigns_updated_at
    before update on campaigns
    for each row execute procedure set_updated_at();

drop trigger if exists profile_updated_at on profile;
create trigger profile_updated_at
    before update on profile
    for each row execute procedure set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profile (id)
    values (new.id)
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure public.handle_new_user();

alter table segments enable row level security;
alter table templates enable row level security;
alter table contacts enable row level security;
alter table campaigns enable row level security;
alter table profile enable row level security;

create policy "Authenticated users can read segments" on segments
    for select to authenticated using (true);
create policy "Authenticated users can read templates" on templates
    for select to authenticated using (true);
create policy "Authenticated users can read contacts" on contacts
    for select to authenticated using (true);
create policy "Authenticated users can read campaigns" on campaigns
    for select to authenticated using (true);

create policy "Users can read their profile" on profile
    for select to authenticated using (auth.uid() = id);
create policy "Users can update their profile" on profile
    for update to authenticated using (auth.uid() = id);
create policy "Users can insert their profile" on profile
    for insert to authenticated with check (auth.uid() = id);
